name: Unit Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Test
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install
        run: npm ci
      - name: Run Tests
        run: npm run test
